/**
 * Team keywords mapping for sport detection
 * Teams are listed with their official names and common abbreviations/nicknames
 */

// MLB Teams (all 30 teams)
export const mlbTeams = [
  "Yankees", "NY Yankees", "New York Yankees",
  "Red Sox", "Boston Red Sox",
  "Blue Jays", "Toronto Blue Jays",
  "Rays", "Tampa Bay Rays",
  "Orioles", "Baltimore Orioles",
  "Guardians", "Cleveland Guardians", "Indians", "Cleveland Indians", 
  "Twins", "Minnesota Twins",
  "White Sox", "Chicago White Sox", "ChiSox",
  "Tigers", "Detroit Tigers",
  "Royals", "Kansas City Royals", "KC Royals",
  "Astros", "Houston Astros",
  "Angels", "Los Angeles Angels", "LA Angels", "Anaheim Angels",
  "Mariners", "Seattle Mariners",
  "Rangers", "Texas Rangers",
  "Athletics", "Oakland Athletics", "A's", "Oakland A's",
  "Braves", "Atlanta Braves",
  "Mets", "New York Mets", "NY Mets",
  "Phillies", "Philadelphia Phillies",
  "Marlins", "Miami Marlins",
  "Nationals", "Washington Nationals", "Nats",
  "Cardinals", "St. Louis Cardinals",
  "Brewers", "Milwaukee Brewers",
  "Cubs", "Chicago Cubs",
  "Reds", "Cincinnati Reds",
  "Pirates", "Pittsburgh Pirates",
  "Dodgers", "Los Angeles Dodgers", "LA Dodgers",
  "Padres", "San Diego Padres", "SD Padres",
  "Giants", "San Francisco Giants", "SF Giants",
  "Diamondbacks", "Arizona Diamondbacks", "D-backs",
  "Rockies", "Colorado Rockies"
];

// NBA Teams (all 30 teams)
export const nbaTeams = [
  "Hawks", "Atlanta Hawks",
  "Celtics", "Boston Celtics",
  "Nets", "Brooklyn Nets",
  "Hornets", "Charlotte Hornets",
  "Bulls", "Chicago Bulls",
  "Cavaliers", "Cleveland Cavaliers", "Cavs",
  "Mavericks", "Dallas Mavericks", "Mavs",
  "Nuggets", "Denver Nuggets",
  "Pistons", "Detroit Pistons",
  "Warriors", "Golden State Warriors", "GSW",
  "Rockets", "Houston Rockets",
  "Pacers", "Indiana Pacers",
  "Clippers", "Los Angeles Clippers", "LA Clippers",
  "Lakers", "Los Angeles Lakers", "LA Lakers",
  "Grizzlies", "Memphis Grizzlies",
  "Heat", "Miami Heat",
  "Bucks", "Milwaukee Bucks",
  "Timberwolves", "Minnesota Timberwolves", "Wolves",
  "Pelicans", "New Orleans Pelicans", "NOLA",
  "Knicks", "New York Knicks", "NY Knicks",
  "Thunder", "Oklahoma City Thunder", "OKC",
  "Magic", "Orlando Magic",
  "76ers", "Philadelphia 76ers", "Sixers", "Philly",
  "Suns", "Phoenix Suns",
  "Trail Blazers", "Portland Trail Blazers", "Blazers",
  "Kings", "Sacramento Kings",
  "Spurs", "San Antonio Spurs",
  "Raptors", "Toronto Raptors",
  "Jazz", "Utah Jazz",
  "Wizards", "Washington Wizards"
];

// NFL Teams (all 32 teams)
export const nflTeams = [
  "Cardinals", "Arizona Cardinals",
  "Falcons", "Atlanta Falcons",
  "Ravens", "Baltimore Ravens",
  "Bills", "Buffalo Bills",
  "Panthers", "Carolina Panthers",
  "Bears", "Chicago Bears",
  "Bengals", "Cincinnati Bengals",
  "Browns", "Cleveland Browns",
  "Cowboys", "Dallas Cowboys",
  "Broncos", "Denver Broncos",
  "Lions", "Detroit Lions",
  "Packers", "Green Bay Packers",
  "Texans", "Houston Texans",
  "Colts", "Indianapolis Colts",
  "Jaguars", "Jacksonville Jaguars", "Jags",
  "Chiefs", "Kansas City Chiefs", "KC Chiefs",
  "Raiders", "Las Vegas Raiders", "LV Raiders", "Oakland Raiders",
  "Chargers", "Los Angeles Chargers", "LA Chargers",
  "Rams", "Los Angeles Rams", "LA Rams",
  "Dolphins", "Miami Dolphins",
  "Vikings", "Minnesota Vikings",
  "Patriots", "New England Patriots", "Pats",
  "Saints", "New Orleans Saints",
  "Giants", "New York Giants", "NY Giants",
  "Jets", "New York Jets", "NY Jets",
  "Eagles", "Philadelphia Eagles", "Philly Eagles",
  "Steelers", "Pittsburgh Steelers",
  "49ers", "San Francisco 49ers", "Niners",
  "Seahawks", "Seattle Seahawks",
  "Buccaneers", "Tampa Bay Buccaneers", "Bucs",
  "Titans", "Tennessee Titans",
  "Commanders", "Washington Commanders", "Washington Football Team", "Redskins"
];

// NHL Teams (all 32 teams)
export const nhlTeams = [
  "Ducks", "Anaheim Ducks",
  "Coyotes", "Arizona Coyotes",
  "Bruins", "Boston Bruins",
  "Sabres", "Buffalo Sabres",
  "Flames", "Calgary Flames",
  "Hurricanes", "Carolina Hurricanes", "Canes",
  "Blackhawks", "Chicago Blackhawks",
  "Avalanche", "Colorado Avalanche", "Avs",
  "Blue Jackets", "Columbus Blue Jackets", "CBJ",
  "Stars", "Dallas Stars",
  "Red Wings", "Detroit Red Wings",
  "Oilers", "Edmonton Oilers",
  "Panthers", "Florida Panthers",
  "Kings", "Los Angeles Kings", "LA Kings",
  "Wild", "Minnesota Wild",
  "Canadiens", "Montreal Canadiens", "Habs",
  "Predators", "Nashville Predators", "Preds",
  "Devils", "New Jersey Devils", "NJ Devils",
  "Islanders", "New York Islanders", "NY Islanders",
  "Rangers", "New York Rangers", "NY Rangers",
  "Senators", "Ottawa Senators", "Sens",
  "Flyers", "Philadelphia Flyers",
  "Penguins", "Pittsburgh Penguins", "Pens",
  "Sharks", "San Jose Sharks",
  "Kraken", "Seattle Kraken",
  "Blues", "St. Louis Blues",
  "Lightning", "Tampa Bay Lightning", "Bolts",
  "Maple Leafs", "Toronto Maple Leafs", "Leafs",
  "Canucks", "Vancouver Canucks",
  "Golden Knights", "Vegas Golden Knights", "VGK", "Knights",
  "Capitals", "Washington Capitals", "Caps",
  "Jets", "Winnipeg Jets"
];

// NCAAF Teams (Top 263)
export const ncaafTeams = [
  "Alabama", "Bama", "Crimson Tide", "Alabama Crimson Tide",
  "Georgia", "UGA", "Bulldogs", "Georgia Bulldogs",
  "Ohio State", "OSU", "Buckeyes", "Ohio State Buckeyes",
  "Michigan", "Wolverines", "Michigan Wolverines",
  "Texas", "Longhorns", "Texas Longhorns",
  "Penn State", "PSU", "Nittany Lions", "Penn State Nittany Lions",
  "Oregon", "Ducks", "Oregon Ducks",
  "Florida State", "FSU", "Seminoles", "Florida State Seminoles",
  "LSU", "Tigers", "LSU Tigers",
  "Notre Dame", "Fighting Irish", "Notre Dame Fighting Irish",
  "Clemson", "Clemson Tigers",
  "Oklahoma", "Sooners", "Oklahoma Sooners",
  "Miami", "Hurricanes", "Miami Hurricanes", "The U",
  "Tennessee", "Volunteers", "Tennessee Volunteers", "Vols",
  "USC", "Trojans", "USC Trojans", "Southern California",
  "Ole Miss", "Rebels", "Ole Miss Rebels", "Mississippi",
  "Texas A&M", "Aggies", "Texas A&M Aggies",
  "Wisconsin", "Badgers", "Wisconsin Badgers",
  "Washington", "Huskies", "Washington Huskies",
  "Iowa", "Hawkeyes", "Iowa Hawkeyes",
  "Auburn", "Auburn Tigers", "War Eagle",
  "Michigan State", "MSU", "Spartans", "Michigan State Spartans",
  "Florida", "Gators", "Florida Gators",
  "UCLA", "Bruins", "UCLA Bruins",
  "Oklahoma State", "OSU", "Cowboys", "Oklahoma State Cowboys",
  "Utah", "Utes", "Utah Utes",
  "Kentucky", "Wildcats", "Kentucky Wildcats",
  "Oregon State", "Beavers", "Oregon State Beavers",
  "Kansas State", "KSU", "Wildcats", "Kansas State Wildcats",
  "South Carolina", "Gamecocks", "South Carolina Gamecocks",
  "North Carolina", "UNC", "Tar Heels", "North Carolina Tar Heels",
  "Minnesota", "Golden Gophers", "Minnesota Golden Gophers", "Gophers",
  "Mississippi State", "MSU", "Bulldogs", "Mississippi State Bulldogs",
  "Arkansas", "Razorbacks", "Arkansas Razorbacks", "Hogs",
  "Iowa State", "Cyclones", "Iowa State Cyclones",
  "Baylor", "Bears", "Baylor Bears",
  "Nebraska", "Cornhuskers", "Nebraska Cornhuskers", "Huskers",
  "Purdue", "Boilermakers", "Purdue Boilermakers",
  "Pittsburgh", "Pitt", "Panthers", "Pittsburgh Panthers",
  "NC State", "Wolfpack", "NC State Wolfpack", "North Carolina State",
  "Illinois", "Fighting Illini", "Illinois Fighting Illini", "Illini",
  "West Virginia", "WVU", "Mountaineers", "West Virginia Mountaineers",
  "UCF", "Knights", "UCF Knights", "Central Florida",
  "Cincinnati", "Bearcats", "Cincinnati Bearcats",
  "Maryland", "Terrapins", "Maryland Terrapins", "Terps",
  "SMU", "Mustangs", "SMU Mustangs", "Southern Methodist",
  "Duke", "Blue Devils", "Duke Blue Devils",
  "BYU", "Cougars", "BYU Cougars", "Brigham Young",
  "Virginia Tech", "VT", "Hokies", "Virginia Tech Hokies",
  "Arizona State", "ASU", "Sun Devils", "Arizona State Sun Devils",
  
  "Arizona", "Wildcats", "Arizona Wildcats",
  "Appalachian State", "App State", "Mountaineers", "Appalachian State Mountaineers",
  "Army", "Black Knights", "Army Black Knights",
  "Ball State", "Cardinals", "Ball State Cardinals",
  "Baylor", "Bears", "Baylor Bears",
  "Boise State", "Broncos", "Boise State Broncos",
  "Boston College", "BC", "Eagles", "Boston College Eagles",
  "Bowling Green", "BGSU", "Falcons", "Bowling Green Falcons",
  "Buffalo", "Bulls", "Buffalo Bulls",
  "California", "Cal", "Golden Bears", "California Golden Bears",
  "Central Michigan", "CMU", "Chippewas", "Central Michigan Chippewas",
  "Charlotte", "49ers", "Charlotte 49ers",
  "Colorado State", "CSU", "Rams", "Colorado State Rams",
  "Connecticut", "UConn", "Huskies", "UConn Huskies",
  "East Carolina", "ECU", "Pirates", "East Carolina Pirates",
  "Eastern Michigan", "EMU", "Eagles", "Eastern Michigan Eagles",
  "Florida Atlantic", "FAU", "Owls", "Florida Atlantic Owls",
  "Florida International", "FIU", "Panthers", "FIU Panthers",
  "Fresno State", "Bulldogs", "Fresno State Bulldogs",
  "Georgia Southern", "Eagles", "Georgia Southern Eagles",
  "Georgia State", "Panthers", "Georgia State Panthers",
  "Georgia Tech", "Yellow Jackets", "Georgia Tech Yellow Jackets",
  "Hawaii", "Rainbow Warriors", "Hawaii Rainbow Warriors",
  "Houston", "Cougars", "Houston Cougars",
  "Idaho", "Vandals", "Idaho Vandals",
  "Illinois", "Fighting Illini", "Illinois Fighting Illini",
  "Indiana", "Hoosiers", "Indiana Hoosiers",
  "Iowa State", "Cyclones", "Iowa State Cyclones",
  "Kansas", "Jayhawks", "Kansas Jayhawks",
  "Kent State", "Golden Flashes", "Kent State Golden Flashes",
  "Liberty", "Flames", "Liberty Flames",
  "Louisiana", "Ragin' Cajuns", "Louisiana Ragin' Cajuns", "ULL",
  "Louisiana Monroe", "ULM", "Warhawks", "Louisiana Monroe Warhawks",
  "Louisiana Tech", "Bulldogs", "Louisiana Tech Bulldogs",
  "Marshall", "Thundering Herd", "Marshall Thundering Herd",
  "Maryland", "Terrapins", "Maryland Terrapins", "Terps",
  "Memphis", "Tigers", "Memphis Tigers",
  "Miami (OH)", "RedHawks", "Miami RedHawks",
  "Middle Tennessee", "MTSU", "Blue Raiders", "Middle Tennessee Blue Raiders",
  "Navy", "Midshipmen", "Navy Midshipmen",
  "Nevada", "Wolf Pack", "Nevada Wolf Pack",
  "New Mexico", "Lobos", "New Mexico Lobos",
  "New Mexico State", "NMSU", "Aggies", "New Mexico State Aggies",
  "North Texas", "Mean Green", "North Texas Mean Green",
  "Northern Illinois", "NIU", "Huskies", "Northern Illinois Huskies",
  "Northwestern", "Wildcats", "Northwestern Wildcats",
  "Ohio", "Bobcats", "Ohio Bobcats",
  "Old Dominion", "ODU", "Monarchs", "Old Dominion Monarchs",
  "Oregon State", "Beavers", "Oregon State Beavers",
  "Penn State", "PSU", "Nittany Lions", "Penn State Nittany Lions",
  "Pittsburgh", "Pitt", "Panthers", "Pittsburgh Panthers",
  "Rice", "Owls", "Rice Owls",
  "Rutgers", "Scarlet Knights", "Rutgers Scarlet Knights",
  "San Diego State", "SDSU", "Aztecs", "San Diego State Aztecs",
  "San Jose State", "SJSU", "Spartans", "San Jose State Spartans",
  "South Alabama", "Jaguars", "South Alabama Jaguars",
  "South Carolina", "Gamecocks", "South Carolina Gamecocks",
  "South Florida", "USF", "Bulls", "South Florida Bulls",
  "Southern Miss", "Golden Eagles", "Southern Miss Golden Eagles",
  "Stanford", "Cardinal", "Stanford Cardinal",
  "Syracuse", "Orange", "Syracuse Orange",
  "TCU", "Horned Frogs", "TCU Horned Frogs", "Texas Christian",
  "Temple", "Owls", "Temple Owls",
  "Texas State", "Bobcats", "Texas State Bobcats",
  "Toledo", "Rockets", "Toledo Rockets",
  "Troy", "Trojans", "Troy Trojans",
  "Tulane", "Green Wave", "Tulane Green Wave",
  "Tulsa", "Golden Hurricane", "Tulsa Golden Hurricane",
  "UAB", "Blazers", "UAB Blazers", "Alabama-Birmingham",
  "UCF", "Knights", "UCF Knights", "Central Florida",
  "UCLA", "Bruins", "UCLA Bruins",
  "UNLV", "Rebels", "UNLV Rebels", "Nevada-Las Vegas",
  "USC", "Trojans", "USC Trojans", "Southern Cal",
  "UTEP", "Miners", "UTEP Miners", "Texas-El Paso",
  "UTSA", "Roadrunners", "UTSA Roadrunners", "Texas-San Antonio",
  "Utah State", "Aggies", "Utah State Aggies",
  "Vanderbilt", "Commodores", "Vanderbilt Commodores", "Vandy",
  "Virginia", "Cavaliers", "Virginia Cavaliers", "UVA", "Wahoos", "Hoos",
  "Virginia Tech", "VT", "Hokies", "Virginia Tech Hokies",
  "Wake Forest", "Demon Deacons", "Wake Forest Demon Deacons",
  "Washington State", "WSU", "Cougars", "Washington State Cougars",
  "Western Kentucky", "WKU", "Hilltoppers", "Western Kentucky Hilltoppers",
  "Western Michigan", "WMU", "Broncos", "Western Michigan Broncos",
  "Wyoming", "Cowboys", "Wyoming Cowboys"
];

// NCAAB Teams (Top 365)
export const ncaabTeams = [
  "Duke", "Blue Devils", "Duke Blue Devils",
  "North Carolina", "UNC", "Tar Heels", "North Carolina Tar Heels",
  "Kansas", "Jayhawks", "Kansas Jayhawks",
  "Kentucky", "Wildcats", "Kentucky Wildcats",
  "UCLA", "Bruins", "UCLA Bruins",
  "Gonzaga", "Bulldogs", "Gonzaga Bulldogs", "Zags",
  "Villanova", "Wildcats", "Villanova Wildcats", "Nova",
  "Michigan", "Wolverines", "Michigan Wolverines",
  "Baylor", "Bears", "Baylor Bears",
  "Arizona", "Wildcats", "Arizona Wildcats",
  "Houston", "Cougars", "Houston Cougars",
  "UConn", "Huskies", "UConn Huskies", "Connecticut",
  "Michigan State", "MSU", "Spartans", "Michigan State Spartans",
  "Purdue", "Boilermakers", "Purdue Boilermakers",
  "Indiana", "Hoosiers", "Indiana Hoosiers", "IU",
  "Texas", "Longhorns", "Texas Longhorns",
  "Louisville", "Cardinals", "Louisville Cardinals",
  "Arkansas", "Razorbacks", "Arkansas Razorbacks", "Hogs",
  "Alabama", "Crimson Tide", "Alabama Crimson Tide",
  "Tennessee", "Volunteers", "Tennessee Volunteers", "Vols",
  "Auburn", "Tigers", "Auburn Tigers",
  "Wisconsin", "Badgers", "Wisconsin Badgers",
  "Iowa", "Hawkeyes", "Iowa Hawkeyes",
  "Syracuse", "Orange", "Syracuse Orange",
  "Illinois", "Fighting Illini", "Illinois Fighting Illini", "Illini",
  "Florida", "Gators", "Florida Gators",
  "Ohio State", "OSU", "Buckeyes", "Ohio State Buckeyes",
  "Maryland", "Terrapins", "Maryland Terrapins", "Terps",
  "Xavier", "Musketeers", "Xavier Musketeers",
  "Creighton", "Bluejays", "Creighton Bluejays",
  "Texas Tech", "Red Raiders", "Texas Tech Red Raiders",
  "Oklahoma", "Sooners", "Oklahoma Sooners",
  "Memphis", "Tigers", "Memphis Tigers",
  "Marquette", "Golden Eagles", "Marquette Golden Eagles",
  "Oregon", "Ducks", "Oregon Ducks",
  "Iowa State", "Cyclones", "Iowa State Cyclones",
  "Providence", "Friars", "Providence Friars",
  "Virginia", "Cavaliers", "Virginia Cavaliers", "Hoos", "Wahoos",
  "West Virginia", "WVU", "Mountaineers", "West Virginia Mountaineers",
  "Saint Mary's", "Gaels", "Saint Mary's Gaels",
  "Florida State", "FSU", "Seminoles", "Florida State Seminoles",
  "Georgetown", "Hoyas", "Georgetown Hoyas",
  "NC State", "Wolfpack", "NC State Wolfpack", "North Carolina State",
  "Seton Hall", "Pirates", "Seton Hall Pirates",
  "USC", "Trojans", "USC Trojans", "Southern California",
  "Notre Dame", "Fighting Irish", "Notre Dame Fighting Irish",
  "Saint Louis", "Billikens", "Saint Louis Billikens",
  "Butler", "Bulldogs", "Butler Bulldogs",
  "Davidson", "Wildcats", "Davidson Wildcats",
  "Dayton", "Flyers", "Dayton Flyers",
  
  "Akron", "Zips", "Akron Zips",
  "Alabama Birmingham", "UAB", "Blazers", "UAB Blazers",
  "Albany", "Great Danes", "Albany Great Danes",
  "American", "Eagles", "American Eagles",
  "Appalachian State", "App State", "Mountaineers", "Appalachian State Mountaineers",
  "Arizona State", "ASU", "Sun Devils", "Arizona State Sun Devils",
  "Arkansas Little Rock", "Little Rock", "Trojans", "Little Rock Trojans",
  "Arkansas Pine Bluff", "Golden Lions", "Arkansas Pine Bluff Golden Lions",
  "Arkansas State", "Red Wolves", "Arkansas State Red Wolves",
  "Army", "Black Knights", "Army Black Knights",
  "Austin Peay", "Governors", "Austin Peay Governors",
  "Ball State", "Cardinals", "Ball State Cardinals",
  "Belmont", "Bruins", "Belmont Bruins",
  "Bethune Cookman", "Wildcats", "Bethune Cookman Wildcats",
  "Binghamton", "Bearcats", "Binghamton Bearcats",
  "Boise State", "Broncos", "Boise State Broncos",
  "Boston College", "BC", "Eagles", "Boston College Eagles",
  "Boston University", "BU", "Terriers", "Boston University Terriers",
  "Bowling Green", "BGSU", "Falcons", "Bowling Green Falcons",
  "Bradley", "Braves", "Bradley Braves",
  "Brown", "Bears", "Brown Bears",
  "Bryant", "Bulldogs", "Bryant Bulldogs",
  "Bucknell", "Bison", "Bucknell Bison",
  "Buffalo", "Bulls", "Buffalo Bulls",
  "Cal Poly", "Mustangs", "Cal Poly Mustangs",
  "Cal State Bakersfield", "Roadrunners", "Cal State Bakersfield Roadrunners",
  "Cal State Fullerton", "Titans", "Cal State Fullerton Titans",
  "Cal State Northridge", "CSUN", "Matadors", "Cal State Northridge Matadors",
  "California", "Cal", "Golden Bears", "California Golden Bears",
  "Campbell", "Fighting Camels", "Campbell Fighting Camels",
  "Canisius", "Golden Griffins", "Canisius Golden Griffins",
  "Central Arkansas", "Bears", "Central Arkansas Bears",
  "Central Connecticut", "Blue Devils", "Central Connecticut Blue Devils",
  "Central Michigan", "CMU", "Chippewas", "Central Michigan Chippewas",
  "Charleston", "Cougars", "Charleston Cougars", "College of Charleston",
  "Charleston Southern", "Buccaneers", "Charleston Southern Buccaneers",
  "Charlotte", "49ers", "Charlotte 49ers",
  "Chattanooga", "Mocs", "Chattanooga Mocs",
  "Chicago State", "Cougars", "Chicago State Cougars",
  "Cincinnati", "Bearcats", "Cincinnati Bearcats",
  "Citadel", "Bulldogs", "The Citadel Bulldogs",
  "Cleveland State", "Vikings", "Cleveland State Vikings",
  "Coastal Carolina", "Chanticleers", "Coastal Carolina Chanticleers",
  "Colgate", "Raiders", "Colgate Raiders",
  "Colorado", "Buffaloes", "Colorado Buffaloes", "Buffs",
  "Colorado State", "CSU", "Rams", "Colorado State Rams",
  "Columbia", "Lions", "Columbia Lions",
  "Coppin State", "Eagles", "Coppin State Eagles",
  "Cornell", "Big Red", "Cornell Big Red",
  "Dartmouth", "Big Green", "Dartmouth Big Green",
  "Delaware", "Blue Hens", "Delaware Blue Hens",
  "Delaware State", "Hornets", "Delaware State Hornets",
  "Denver", "Pioneers", "Denver Pioneers",
  "DePaul", "Blue Demons", "DePaul Blue Demons",
  "Detroit", "Titans", "Detroit Titans",
  "Drake", "Bulldogs", "Drake Bulldogs",
  "Drexel", "Dragons", "Drexel Dragons",
  "Duke", "Blue Devils", "Duke Blue Devils",
  "Duquesne", "Dukes", "Duquesne Dukes",
  "East Carolina", "ECU", "Pirates", "East Carolina Pirates",
  "East Tennessee State", "ETSU", "Buccaneers", "East Tennessee State Buccaneers",
  "Eastern Illinois", "Panthers", "Eastern Illinois Panthers",
  "Eastern Kentucky", "Colonels", "Eastern Kentucky Colonels",
  "Eastern Michigan", "EMU", "Eagles", "Eastern Michigan Eagles",
  "Eastern Washington", "Eagles", "Eastern Washington Eagles",
  "Elon", "Phoenix", "Elon Phoenix",
  "Evansville", "Purple Aces", "Evansville Purple Aces",
  "Fairfield", "Stags", "Fairfield Stags",
  "Fairleigh Dickinson", "FDU", "Knights", "Fairleigh Dickinson Knights",
  "Florida A&M", "FAMU", "Rattlers", "Florida A&M Rattlers",
  "Florida Atlantic", "FAU", "Owls", "Florida Atlantic Owls",
  "Florida Gulf Coast", "FGCU", "Eagles", "Florida Gulf Coast Eagles",
  "Florida International", "FIU", "Panthers", "FIU Panthers",
  "Fordham", "Rams", "Fordham Rams",
  "Fresno State", "Bulldogs", "Fresno State Bulldogs",
  "Furman", "Paladins", "Furman Paladins",
  "Gardner Webb", "Runnin' Bulldogs", "Gardner Webb Runnin' Bulldogs",
  "George Mason", "Patriots", "George Mason Patriots",
  "George Washington", "GW", "Colonials", "George Washington Colonials",
  "Georgia Southern", "Eagles", "Georgia Southern Eagles",
  "Georgia State", "Panthers", "Georgia State Panthers",
  "Grambling", "Tigers", "Grambling Tigers",
  "Grand Canyon", "Antelopes", "Grand Canyon Antelopes", "Lopes",
  "Green Bay", "Phoenix", "Green Bay Phoenix",
  "Hampton", "Pirates", "Hampton Pirates",
  "Hartford", "Hawks", "Hartford Hawks",
  "Harvard", "Crimson", "Harvard Crimson",
  "Hawaii", "Rainbow Warriors", "Hawaii Rainbow Warriors",
  "High Point", "Panthers", "High Point Panthers",
  "Hofstra", "Pride", "Hofstra Pride",
  "Holy Cross", "Crusaders", "Holy Cross Crusaders",
  "Houston Baptist", "Huskies", "Houston Baptist Huskies",
  "Howard", "Bison", "Howard Bison",
  "Idaho", "Vandals", "Idaho Vandals",
  "Idaho State", "Bengals", "Idaho State Bengals",
  "Illinois Chicago", "UIC", "Flames", "UIC Flames",
  "Illinois State", "Redbirds", "Illinois State Redbirds",
  "Incarnate Word", "Cardinals", "Incarnate Word Cardinals",
  "Indiana State", "Sycamores", "Indiana State Sycamores",
  "Iona", "Gaels", "Iona Gaels",
  "IPFW", "Mastodons", "IPFW Mastodons", "Purdue Fort Wayne",
  "IUPUI", "Jaguars", "IUPUI Jaguars",
  "Jackson State", "Tigers", "Jackson State Tigers",
  "Jacksonville", "Dolphins", "Jacksonville Dolphins",
  "Jacksonville State", "Gamecocks", "Jacksonville State Gamecocks",
  "James Madison", "JMU", "Dukes", "James Madison Dukes",
  "Kansas City", "Roos", "Kansas City Roos", "UMKC",
  "Kent State", "Golden Flashes", "Kent State Golden Flashes"
];

// Combined team keywords export
export const teamKeywords = {
  MLB: mlbTeams,
  NBA: nbaTeams,
  NFL: nflTeams,
  NHL: nhlTeams,
  NCAAF: ncaafTeams,
  NCAAB: ncaabTeams
};

// Map team nicknames to sports for quick lookup
export const sportsMapping = {
  baseball: "MLB",
  basketball: ["NBA", "NCAAB"],
  football: ["NFL", "NCAAF"],
  hockey: "NHL"
};

// Common sport terms for detection
export const sportTerms = {
  baseball: ["mlb", "baseball", "innings", "pitcher", "home run", "ballpark", "batting", "diamond"],
  basketball: ["nba", "ncaa basketball", "ncaab", "basketball", "hoops", "court", "3-pointer", "dunk", "basket", "college basketball"],
  football: ["nfl", "ncaa football", "ncaaf", "football", "touchdown", "field goal", "quarterback", "gridiron", "college football"],
  hockey: ["nhl", "hockey", "ice", "puck", "goal", "rink", "period", "power play"]
};
