
/**
 * Team keywords mapping for sport detection
 * Teams are listed with their official names and common abbreviations/nicknames
 */

// MLB Teams (all 30 teams)
export const mlbTeams = [
  "Yankees", "NY Yankees", "New York Yankees",
  "Red Sox", "Boston Red Sox",
  "Blue Jays", "Toronto Blue Jays",
  "Rays", "Tampa Bay Rays",
  "Orioles", "Baltimore Orioles",
  "Guardians", "Cleveland Guardians", "Indians", "Cleveland Indians", 
  "Twins", "Minnesota Twins",
  "White Sox", "Chicago White Sox", "ChiSox",
  "Tigers", "Detroit Tigers",
  "Royals", "Kansas City Royals", "KC Royals",
  "Astros", "Houston Astros",
  "Angels", "Los Angeles Angels", "LA Angels", "Anaheim Angels",
  "Mariners", "Seattle Mariners",
  "Rangers", "Texas Rangers",
  "Athletics", "Oakland Athletics", "A's", "Oakland A's",
  "Braves", "Atlanta Braves",
  "Mets", "New York Mets", "NY Mets",
  "Phillies", "Philadelphia Phillies",
  "Marlins", "Miami Marlins",
  "Nationals", "Washington Nationals", "Nats",
  "Cardinals", "St. Louis Cardinals",
  "Brewers", "Milwaukee Brewers",
  "Cubs", "Chicago Cubs",
  "Reds", "Cincinnati Reds",
  "Pirates", "Pittsburgh Pirates",
  "Dodgers", "Los Angeles Dodgers", "LA Dodgers",
  "Padres", "San Diego Padres", "SD Padres",
  "Giants", "San Francisco Giants", "SF Giants",
  "Diamondbacks", "Arizona Diamondbacks", "D-backs",
  "Rockies", "Colorado Rockies"
];

// NBA Teams (all 30 teams)
export const nbaTeams = [
  "Hawks", "Atlanta Hawks",
  "Celtics", "Boston Celtics",
  "Nets", "Brooklyn Nets",
  "Hornets", "Charlotte Hornets",
  "Bulls", "Chicago Bulls",
  "Cavaliers", "Cleveland Cavaliers", "Cavs",
  "Mavericks", "Dallas Mavericks", "Mavs",
  "Nuggets", "Denver Nuggets",
  "Pistons", "Detroit Pistons",
  "Warriors", "Golden State Warriors", "GSW",
  "Rockets", "Houston Rockets",
  "Pacers", "Indiana Pacers",
  "Clippers", "Los Angeles Clippers", "LA Clippers",
  "Lakers", "Los Angeles Lakers", "LA Lakers",
  "Grizzlies", "Memphis Grizzlies",
  "Heat", "Miami Heat",
  "Bucks", "Milwaukee Bucks",
  "Timberwolves", "Minnesota Timberwolves", "Wolves",
  "Pelicans", "New Orleans Pelicans", "NOLA",
  "Knicks", "New York Knicks", "NY Knicks",
  "Thunder", "Oklahoma City Thunder", "OKC",
  "Magic", "Orlando Magic",
  "76ers", "Philadelphia 76ers", "Sixers", "Philly",
  "Suns", "Phoenix Suns",
  "Trail Blazers", "Portland Trail Blazers", "Blazers",
  "Kings", "Sacramento Kings",
  "Spurs", "San Antonio Spurs",
  "Raptors", "Toronto Raptors",
  "Jazz", "Utah Jazz",
  "Wizards", "Washington Wizards"
];

// NFL Teams (all 32 teams)
export const nflTeams = [
  "Cardinals", "Arizona Cardinals",
  "Falcons", "Atlanta Falcons",
  "Ravens", "Baltimore Ravens",
  "Bills", "Buffalo Bills",
  "Panthers", "Carolina Panthers",
  "Bears", "Chicago Bears",
  "Bengals", "Cincinnati Bengals",
  "Browns", "Cleveland Browns",
  "Cowboys", "Dallas Cowboys",
  "Broncos", "Denver Broncos",
  "Lions", "Detroit Lions",
  "Packers", "Green Bay Packers",
  "Texans", "Houston Texans",
  "Colts", "Indianapolis Colts",
  "Jaguars", "Jacksonville Jaguars", "Jags",
  "Chiefs", "Kansas City Chiefs", "KC Chiefs",
  "Raiders", "Las Vegas Raiders", "LV Raiders", "Oakland Raiders",
  "Chargers", "Los Angeles Chargers", "LA Chargers",
  "Rams", "Los Angeles Rams", "LA Rams",
  "Dolphins", "Miami Dolphins",
  "Vikings", "Minnesota Vikings",
  "Patriots", "New England Patriots", "Pats",
  "Saints", "New Orleans Saints",
  "Giants", "New York Giants", "NY Giants",
  "Jets", "New York Jets", "NY Jets",
  "Eagles", "Philadelphia Eagles", "Philly Eagles",
  "Steelers", "Pittsburgh Steelers",
  "49ers", "San Francisco 49ers", "Niners",
  "Seahawks", "Seattle Seahawks",
  "Buccaneers", "Tampa Bay Buccaneers", "Bucs",
  "Titans", "Tennessee Titans",
  "Commanders", "Washington Commanders", "Washington Football Team", "Redskins"
];

// NHL Teams (all 32 teams)
export const nhlTeams = [
  "Ducks", "Anaheim Ducks",
  "Coyotes", "Arizona Coyotes",
  "Bruins", "Boston Bruins",
  "Sabres", "Buffalo Sabres",
  "Flames", "Calgary Flames",
  "Hurricanes", "Carolina Hurricanes", "Canes",
  "Blackhawks", "Chicago Blackhawks",
  "Avalanche", "Colorado Avalanche", "Avs",
  "Blue Jackets", "Columbus Blue Jackets", "CBJ",
  "Stars", "Dallas Stars",
  "Red Wings", "Detroit Red Wings",
  "Oilers", "Edmonton Oilers",
  "Panthers", "Florida Panthers",
  "Kings", "Los Angeles Kings", "LA Kings",
  "Wild", "Minnesota Wild",
  "Canadiens", "Montreal Canadiens", "Habs",
  "Predators", "Nashville Predators", "Preds",
  "Devils", "New Jersey Devils", "NJ Devils",
  "Islanders", "New York Islanders", "NY Islanders",
  "Rangers", "New York Rangers", "NY Rangers",
  "Senators", "Ottawa Senators", "Sens",
  "Flyers", "Philadelphia Flyers",
  "Penguins", "Pittsburgh Penguins", "Pens",
  "Sharks", "San Jose Sharks",
  "Kraken", "Seattle Kraken",
  "Blues", "St. Louis Blues",
  "Lightning", "Tampa Bay Lightning", "Bolts",
  "Maple Leafs", "Toronto Maple Leafs", "Leafs",
  "Canucks", "Vancouver Canucks",
  "Golden Knights", "Vegas Golden Knights", "VGK", "Knights",
  "Capitals", "Washington Capitals", "Caps",
  "Jets", "Winnipeg Jets"
];

// NCAAF Teams (Top 50)
export const ncaafTeams = [
  "Alabama", "Bama", "Crimson Tide", "Alabama Crimson Tide",
  "Georgia", "UGA", "Bulldogs", "Georgia Bulldogs",
  "Ohio State", "OSU", "Buckeyes", "Ohio State Buckeyes",
  "Michigan", "Wolverines", "Michigan Wolverines",
  "Texas", "Longhorns", "Texas Longhorns",
  "Penn State", "PSU", "Nittany Lions", "Penn State Nittany Lions",
  "Oregon", "Ducks", "Oregon Ducks",
  "Florida State", "FSU", "Seminoles", "Florida State Seminoles",
  "LSU", "Tigers", "LSU Tigers",
  "Notre Dame", "Fighting Irish", "Notre Dame Fighting Irish",
  "Clemson", "Clemson Tigers",
  "Oklahoma", "Sooners", "Oklahoma Sooners",
  "Miami", "Hurricanes", "Miami Hurricanes", "The U",
  "Tennessee", "Volunteers", "Tennessee Volunteers", "Vols",
  "USC", "Trojans", "USC Trojans", "Southern California",
  "Ole Miss", "Rebels", "Ole Miss Rebels", "Mississippi",
  "Texas A&M", "Aggies", "Texas A&M Aggies",
  "Wisconsin", "Badgers", "Wisconsin Badgers",
  "Washington", "Huskies", "Washington Huskies",
  "Iowa", "Hawkeyes", "Iowa Hawkeyes",
  "Auburn", "Auburn Tigers", "War Eagle",
  "Michigan State", "MSU", "Spartans", "Michigan State Spartans",
  "Florida", "Gators", "Florida Gators",
  "UCLA", "Bruins", "UCLA Bruins",
  "Oklahoma State", "OSU", "Cowboys", "Oklahoma State Cowboys",
  "Utah", "Utes", "Utah Utes",
  "Kentucky", "Wildcats", "Kentucky Wildcats",
  "Oregon State", "Beavers", "Oregon State Beavers",
  "Kansas State", "KSU", "Wildcats", "Kansas State Wildcats",
  "South Carolina", "Gamecocks", "South Carolina Gamecocks",
  "North Carolina", "UNC", "Tar Heels", "North Carolina Tar Heels",
  "Minnesota", "Golden Gophers", "Minnesota Golden Gophers", "Gophers",
  "Mississippi State", "MSU", "Bulldogs", "Mississippi State Bulldogs",
  "Arkansas", "Razorbacks", "Arkansas Razorbacks", "Hogs",
  "Iowa State", "Cyclones", "Iowa State Cyclones",
  "Baylor", "Bears", "Baylor Bears",
  "Nebraska", "Cornhuskers", "Nebraska Cornhuskers", "Huskers",
  "Purdue", "Boilermakers", "Purdue Boilermakers",
  "Pittsburgh", "Pitt", "Panthers", "Pittsburgh Panthers",
  "NC State", "Wolfpack", "NC State Wolfpack", "North Carolina State",
  "Illinois", "Fighting Illini", "Illinois Fighting Illini", "Illini",
  "West Virginia", "WVU", "Mountaineers", "West Virginia Mountaineers",
  "UCF", "Knights", "UCF Knights", "Central Florida",
  "Cincinnati", "Bearcats", "Cincinnati Bearcats",
  "Maryland", "Terrapins", "Maryland Terrapins", "Terps",
  "SMU", "Mustangs", "SMU Mustangs", "Southern Methodist",
  "Duke", "Blue Devils", "Duke Blue Devils",
  "BYU", "Cougars", "BYU Cougars", "Brigham Young",
  "Virginia Tech", "VT", "Hokies", "Virginia Tech Hokies",
  "Arizona State", "ASU", "Sun Devils", "Arizona State Sun Devils"
];

// NCAAB Teams (Top 50)
export const ncaabTeams = [
  "Duke", "Blue Devils", "Duke Blue Devils",
  "North Carolina", "UNC", "Tar Heels", "North Carolina Tar Heels",
  "Kansas", "Jayhawks", "Kansas Jayhawks",
  "Kentucky", "Wildcats", "Kentucky Wildcats",
  "UCLA", "Bruins", "UCLA Bruins",
  "Gonzaga", "Bulldogs", "Gonzaga Bulldogs", "Zags",
  "Villanova", "Wildcats", "Villanova Wildcats", "Nova",
  "Michigan", "Wolverines", "Michigan Wolverines",
  "Baylor", "Bears", "Baylor Bears",
  "Arizona", "Wildcats", "Arizona Wildcats",
  "Houston", "Cougars", "Houston Cougars",
  "UConn", "Huskies", "UConn Huskies", "Connecticut",
  "Michigan State", "MSU", "Spartans", "Michigan State Spartans",
  "Purdue", "Boilermakers", "Purdue Boilermakers",
  "Indiana", "Hoosiers", "Indiana Hoosiers", "IU",
  "Texas", "Longhorns", "Texas Longhorns",
  "Louisville", "Cardinals", "Louisville Cardinals",
  "Arkansas", "Razorbacks", "Arkansas Razorbacks", "Hogs",
  "Alabama", "Crimson Tide", "Alabama Crimson Tide",
  "Tennessee", "Volunteers", "Tennessee Volunteers", "Vols",
  "Auburn", "Tigers", "Auburn Tigers",
  "Wisconsin", "Badgers", "Wisconsin Badgers",
  "Iowa", "Hawkeyes", "Iowa Hawkeyes",
  "Syracuse", "Orange", "Syracuse Orange",
  "Illinois", "Fighting Illini", "Illinois Fighting Illini", "Illini",
  "Florida", "Gators", "Florida Gators",
  "Ohio State", "OSU", "Buckeyes", "Ohio State Buckeyes",
  "Maryland", "Terrapins", "Maryland Terrapins", "Terps",
  "Xavier", "Musketeers", "Xavier Musketeers",
  "Creighton", "Bluejays", "Creighton Bluejays",
  "Texas Tech", "Red Raiders", "Texas Tech Red Raiders",
  "Oklahoma", "Sooners", "Oklahoma Sooners",
  "Memphis", "Tigers", "Memphis Tigers",
  "Marquette", "Golden Eagles", "Marquette Golden Eagles",
  "Oregon", "Ducks", "Oregon Ducks",
  "Iowa State", "Cyclones", "Iowa State Cyclones",
  "Providence", "Friars", "Providence Friars",
  "Virginia", "Cavaliers", "Virginia Cavaliers", "Hoos", "Wahoos",
  "West Virginia", "WVU", "Mountaineers", "West Virginia Mountaineers",
  "Saint Mary's", "Gaels", "Saint Mary's Gaels",
  "Florida State", "FSU", "Seminoles", "Florida State Seminoles",
  "Georgetown", "Hoyas", "Georgetown Hoyas",
  "NC State", "Wolfpack", "NC State Wolfpack", "North Carolina State",
  "Seton Hall", "Pirates", "Seton Hall Pirates",
  "USC", "Trojans", "USC Trojans", "Southern California",
  "Notre Dame", "Fighting Irish", "Notre Dame Fighting Irish",
  "Saint Louis", "Billikens", "Saint Louis Billikens",
  "Butler", "Bulldogs", "Butler Bulldogs",
  "Davidson", "Wildcats", "Davidson Wildcats",
  "Dayton", "Flyers", "Dayton Flyers"
];

// Combined team keywords export
export const teamKeywords = {
  MLB: mlbTeams,
  NBA: nbaTeams,
  NFL: nflTeams,
  NHL: nhlTeams,
  NCAAF: ncaafTeams,
  NCAAB: ncaabTeams
};

// Map team nicknames to sports for quick lookup
export const sportsMapping = {
  baseball: "MLB",
  basketball: ["NBA", "NCAAB"],
  football: ["NFL", "NCAAF"],
  hockey: "NHL"
};

// Common sport terms for detection
export const sportTerms = {
  baseball: ["mlb", "baseball", "innings", "pitcher", "home run", "ballpark", "batting", "diamond"],
  basketball: ["nba", "ncaa basketball", "ncaab", "basketball", "hoops", "court", "3-pointer", "dunk", "basket", "college basketball"],
  football: ["nfl", "ncaa football", "ncaaf", "football", "touchdown", "field goal", "quarterback", "gridiron", "college football"],
  hockey: ["nhl", "hockey", "ice", "puck", "goal", "rink", "period", "power play"]
};
