// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exnpsogbxavhaszlnfvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4bnBzb2dieGF2aGFzemxuZnZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTMzMDQsImV4cCI6MjA2MTE2OTMwNH0.4Y8XCgb6xXRqIqacjfKVU01EEE9Me7ZiHvPsqmrUCeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});